#!/bin/bash

# Auto-Backup Script para Medusa Storefront
# Hace backup completo del código frontend y lo sube a GitHub

set -e

# Colores para output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Medusa Storefront - Auto Backup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
BACKUP_DIR="backups/builds"

# Crear directorio de backups si no existe
mkdir -p "$BACKUP_DIR"

# 1. Verificar si hay cambios
echo -e "${BLUE}[1/4] 🔍 Verificando cambios...${NC}"
git add .

if git diff --cached --quiet; then
    echo -e "${YELLOW}   ℹ️  No hay cambios para respaldar${NC}"
    exit 0
fi

# 2. Mostrar resumen de cambios
echo -e "${GREEN}   ✓ Cambios detectados${NC}"
CHANGES=$(git diff --cached --shortstat)
echo -e "${BLUE}   📊 $CHANGES${NC}"
echo ""

# 3. Crear backup de build si existe
echo -e "${BLUE}[2/4] 📦 Creando backup de build...${NC}"
if [ -d ".next" ]; then
    BUILD_BACKUP="$BACKUP_DIR/build-$(date +"%Y%m%d_%H%M%S").tar.gz"
    tar -czf "$BUILD_BACKUP" .next > /dev/null 2>&1
    echo -e "${GREEN}   ✓ Build respaldado en $BUILD_BACKUP${NC}"

    # Mantener solo los últimos 5 backups de build
    cd "$BACKUP_DIR"
    ls -t build-*.tar.gz 2>/dev/null | tail -n +6 | xargs -r rm --
    cd - > /dev/null
else
    echo -e "${YELLOW}   ⚠️  No hay build para respaldar${NC}"
fi
echo ""

# 4. Crear commit
echo -e "${BLUE}[3/4] 💾 Creando commit...${NC}"
COMMIT_MSG="🔄 Auto-backup Storefront: $TIMESTAMP

Changes: $CHANGES

Frontend backup - Generated by Medusa Auto-Backup System"

if git commit -m "$COMMIT_MSG" > /dev/null 2>&1; then
    echo -e "${GREEN}   ✓ Commit creado exitosamente${NC}"
    COMMIT_HASH=$(git rev-parse --short HEAD)
    echo -e "${BLUE}   📌 Commit: $COMMIT_HASH${NC}"
else
    echo -e "${RED}   ✗ Error al crear commit${NC}"
    exit 1
fi
echo ""

# 5. Push a GitHub
echo -e "${BLUE}[4/4] 🚀 Subiendo a GitHub...${NC}"
BRANCH=$(git branch --show-current)

if git push origin "$BRANCH" --quiet 2>/dev/null; then
    echo -e "${GREEN}   ✓ Push exitoso a origin/$BRANCH${NC}"
else
    echo -e "${YELLOW}   ⚠️  Push falló - cambios guardados localmente${NC}"
    echo -e "${YELLOW}   💡 Ejecuta manualmente: git push origin $BRANCH${NC}"
fi

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  ✅ Backup Completado${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}   📅 Timestamp: $TIMESTAMP${NC}"
echo -e "${BLUE}   📌 Commit: $COMMIT_HASH${NC}"
echo -e "${BLUE}   🌿 Branch: $BRANCH${NC}"
echo ""
